### ISSUE TITLE
Support for more environments than development and production

### ISSUE THREAD

**Issue by frekw** [joliss/broccoli-env#2]
Hi,

In the Ember app we're building, we have separate environments for dev, staging, qa and production.

All requests to our API is done using CORS, which means that we need to use API hostnames depending on the environment we're building for. At the moment, ember-cli supports this in the Brocfile. However, since broccoli-env disallows any environment that isn't dev or prod, it doesn't work.

https://github.com/joliss/broccoli-env/pull/1 is relevant here, but I thought this might warrant its own use case.

So my question generally boils down to: do the environments need to be limited at all?

**Comment by rwjblue** [comment]
As of 0.0.25 Ember CLI no longer uses `broccoli-env`, and instead does this internally (using the `EMBER_ENV` environment variable).

See https://github.com/stefanpenner/ember-cli/pull/429 for details.

**Comment by frekw** [comment]
Oh, cool. Thanks @rjackson. Closing this, then.
